-- Seed all 28 supplements into the products table
-- Run after 20260321_create_core_tables.sql and 20260321_extend_tables.sql

INSERT INTO public.products (name, description, unit_cost, category_tags, timing_schedule, evidence_level, citation_count, dosage_amount, dosage_unit, dosage_form, price_per_month)
VALUES
  ('L-Theanine', 'Suntheanine (patented pure L-isomer form)', 8.00, ARRAY['cognitive', 'focus', 'calm-alertness', 'attention'], 'AM', 'A', 42, 200, 'mg', 'Suntheanine (patented pure L-isomer form)', 8.00),
  ('Lion''s Mane (Hericium erinaceus)', 'Dual-extracted fruiting body standardized to 30% beta-glucans and hericenones', 22.00, ARRAY['cognitive', 'neurogenesis', 'memory', 'nerve-growth-factor'], 'AM', 'B', 28, 1000, 'mg', 'Dual-extracted fruiting body standardized to 30% beta-glucans and hericenones', 22.00),
  ('Bacopa Monnieri', 'Standardized to 50% bacosides (Bacognize or Synapsa extract)', 12.00, ARRAY['cognitive', 'memory-consolidation', 'learning', 'neuroprotection'], 'AM', 'A', 36, 300, 'mg', 'Standardized to 50% bacosides (Bacognize or Synapsa extract)', 12.00),
  ('Alpha-GPC', 'Alpha-glycerylphosphorylcholine 50% granular', 16.00, ARRAY['cognitive', 'acetylcholine-synthesis', 'focus', 'working-memory'], 'AM', 'A', 31, 300, 'mg', 'Alpha-glycerylphosphorylcholine 50% granular', 16.00),
  ('Phosphatidylserine', 'Soy-free sunflower-derived phosphatidylserine (Sharp-PS)', 14.00, ARRAY['cognitive', 'cortisol-regulation', 'memory', 'cell-membrane-integrity'], 'AM', 'A', 34, 100, 'mg', 'Soy-free sunflower-derived phosphatidylserine (Sharp-PS)', 14.00),
  ('Magnesium Bisglycinate', 'Chelated magnesium bisglycinate (providing ~80mg elemental magnesium)', 10.00, ARRAY['sleep-stress', 'sleep-quality', 'muscle-relaxation', 'stress-reduction'], 'PM', 'A', 48, 400, 'mg', 'Chelated magnesium bisglycinate (providing ~80mg elemental magnesium)', 10.00),
  ('Ashwagandha KSM-66', 'KSM-66 full-spectrum root extract standardized to 5% withanolides', 14.00, ARRAY['sleep-stress', 'cortisol-reduction', 'stress-resilience', 'thyroid-support'], 'PM', 'A', 52, 600, 'mg', 'KSM-66 full-spectrum root extract standardized to 5% withanolides', 14.00),
  ('Apigenin', 'Extracted from chamomile (Matricaria chamomilla), high-purity crystalline apigenin', 8.00, ARRAY['sleep-stress', 'sleep-onset', 'gaba-modulation', 'anxiolysis'], 'PM', 'B', 18, 50, 'mg', 'Extracted from chamomile (Matricaria chamomilla), high-purity crystalline apigenin', 8.00),
  ('L-Tryptophan', 'Pharmaceutical-grade free-form L-tryptophan', 10.00, ARRAY['sleep-stress', 'serotonin-synthesis', 'melatonin-precursor', 'mood-support'], 'PM', 'A', 38, 500, 'mg', 'Pharmaceutical-grade free-form L-tryptophan', 10.00),
  ('Glycine', 'Pharmaceutical-grade free-form glycine powder', 6.00, ARRAY['sleep-stress', 'sleep-architecture', 'core-body-temperature', 'next-day-alertness'], 'PM', 'A', 22, 3, 'g', 'Pharmaceutical-grade free-form glycine powder', 6.00),
  ('NMN (Nicotinamide Mononucleotide)', 'Enzymatically synthesized beta-nicotinamide mononucleotide, >99% purity', 28.00, ARRAY['longevity', 'nad-plus-biosynthesis', 'cellular-energy', 'dna-repair'], 'AM', 'B', 45, 500, 'mg', 'Enzymatically synthesized beta-nicotinamide mononucleotide, >99% purity', 28.00),
  ('Trans-Resveratrol', 'Micronized trans-resveratrol from Polygonum cuspidatum, >98% purity', 22.00, ARRAY['longevity', 'sirtuin-activation', 'antioxidant-defense', 'cardiovascular-health'], 'AM', 'B', 64, 500, 'mg', 'Micronized trans-resveratrol from Polygonum cuspidatum, >98% purity', 22.00),
  ('CoQ10 Ubiquinol', 'Kaneka Ubiquinol (reduced form of CoQ10) in lipid-based softgel', 24.00, ARRAY['longevity', 'mitochondrial-function', 'cellular-energy', 'cardiovascular-health'], 'AM', 'A', 78, 200, 'mg', 'Kaneka Ubiquinol (reduced form of CoQ10) in lipid-based softgel for enhanced absorption', 24.00),
  ('PQQ (Pyrroloquinoline Quinone)', 'BioPQQ (natural fermentation-derived pyrroloquinoline quinone disodium salt)', 18.00, ARRAY['longevity', 'mitochondrial-biogenesis', 'neuroprotection', 'nerve-growth-factor'], 'AM', 'B', 19, 20, 'mg', 'BioPQQ (natural fermentation-derived pyrroloquinoline quinone disodium salt)', 18.00),
  ('Astaxanthin', 'Derived from Haematococcus pluvialis microalgae, supercritical CO2 extracted', 16.00, ARRAY['longevity', 'antioxidant-defense', 'skin-protection', 'eye-health'], 'AM', 'B', 33, 12, 'mg', 'Derived from Haematococcus pluvialis microalgae, supercritical CO2 extracted', 16.00),
  ('Phytoceramides', 'Rice-derived phytoceramides (Ceramide-PCD) standardized to glucosylceramides', 16.00, ARRAY['skin-radiance', 'skin-barrier', 'hydration', 'anti-wrinkle'], 'AM', 'B', 14, 350, 'mg', 'Rice-derived phytoceramides (Ceramide-PCD) standardized to glucosylceramides', 16.00),
  ('Hyaluronic Acid', 'Low molecular weight hyaluronic acid (< 100 kDa) for enhanced oral bioavailability', 14.00, ARRAY['skin-radiance', 'skin-hydration', 'joint-lubrication', 'dermal-volume'], 'AM', 'B', 21, 200, 'mg', 'Low molecular weight hyaluronic acid (< 100 kDa) for enhanced oral bioavailability', 14.00),
  ('Vitamin C Liposomal', 'Liposomal-encapsulated ascorbic acid in phospholipid vesicles', 18.00, ARRAY['skin-radiance', 'collagen-synthesis', 'antioxidant-defense', 'immune-support'], 'AM', 'A', 56, 1000, 'mg', 'Liposomal-encapsulated ascorbic acid in phospholipid vesicles', 18.00),
  ('Collagen Peptides (Type I & III)', 'Hydrolyzed bovine collagen peptides (Type I & III), enzymatically broken to 2-5 kDa', 22.00, ARRAY['skin-radiance', 'skin-elasticity', 'hair-strength', 'nail-growth'], 'AM/PM', 'A', 41, 10, 'g', 'Hydrolyzed bovine collagen peptides (Type I & III), enzymatically broken to 2-5 kDa for optimal absorption', 22.00),
  ('Vitamin D3', 'Cholecalciferol from lanolin, microencapsulated in MCT oil', 6.00, ARRAY['foundation', 'bone-density', 'immune-modulation', 'mood-support'], 'AM', 'A', 92, 5000, 'IU', 'Cholecalciferol from lanolin, microencapsulated in MCT oil for fat-soluble absorption', 6.00),
  ('Vitamin K2 MK-7', 'MenaQ7 all-trans menaquinone-7 from Bacillus subtilis natto fermentation', 10.00, ARRAY['foundation', 'calcium-metabolism', 'bone-density', 'cardiovascular-protection'], 'AM', 'A', 37, 200, 'mcg', 'MenaQ7 all-trans menaquinone-7 from Bacillus subtilis natto fermentation', 10.00),
  ('Omega-3 EPA/DHA', 'Triglyceride-form fish oil (wild-caught small fish), IFOS 5-star certified', 18.00, ARRAY['foundation', 'cardiovascular-health', 'anti-inflammatory', 'brain-health'], 'AM', 'A', 124, 2000, 'mg', 'Triglyceride-form fish oil (wild-caught small fish), providing 1200mg EPA + 800mg DHA, IFOS 5-star certified', 18.00),
  ('Zinc Picolinate', 'Zinc picolinate chelate (providing ~7mg elemental zinc per capsule)', 8.00, ARRAY['foundation', 'immune-function', 'testosterone-support', 'skin-health'], 'AM', 'A', 58, 30, 'mg', 'Zinc picolinate chelate (providing ~7mg elemental zinc per capsule)', 8.00),
  ('B-Complex Methylated', 'Full-spectrum methylated B-complex', 14.00, ARRAY['foundation', 'energy-metabolism', 'methylation', 'homocysteine-regulation'], 'AM', 'A', 67, 1, 'mg', 'Full-spectrum methylated B-complex: B1 benfotiamine, B2 riboflavin-5-phosphate, B6 pyridoxal-5-phosphate, B9 L-methylfolate, B12 methylcobalamin', 14.00),
  ('Selenium', 'SelenoExcell high-selenium yeast providing selenomethionine', 7.00, ARRAY['foundation', 'thyroid-function', 'antioxidant-defense', 'immune-support'], 'AM', 'A', 44, 200, 'mcg', 'SelenoExcell high-selenium yeast providing selenomethionine and full spectrum of selenium species', 7.00),
  ('Rhodiola Rosea', 'Standardized to 3% rosavins and 1% salidroside (SHR-5 extract)', 12.00, ARRAY['performance', 'physical-endurance', 'mental-stamina', 'stress-adaptation'], 'AM', 'A', 39, 400, 'mg', 'Standardized to 3% rosavins and 1% salidroside (SHR-5 extract)', 12.00),
  ('Creatine Monohydrate', 'Creapure micronized creatine monohydrate (German-manufactured, HPLC tested)', 8.00, ARRAY['performance', 'atp-regeneration', 'strength', 'cognitive-performance'], 'AM/PM', 'A', 186, 5, 'g', 'Creapure micronized creatine monohydrate (German-manufactured, HPLC tested for purity)', 8.00),
  ('Cordyceps Militaris', 'Fruiting body extract standardized to 0.3% cordycepin and 25% beta-glucans', 18.00, ARRAY['performance', 'oxygen-utilization', 'endurance', 'atp-production'], 'AM', 'B', 24, 1000, 'mg', 'Fruiting body extract standardized to 0.3% cordycepin and 25% beta-glucans', 18.00)
ON CONFLICT DO NOTHING;
